name: PR ci

on: 
  pull_request: 
    branches: 
      - master
      - main 
    types: 
      - edited
      - synchronize
      - opened
      - ready_for_review
      - reopened

permissions: 
  contents: read
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps: 
      - name: Add PR Comment
        uses: actions/first-interaction@v1.2.0
        if: github.actor != 'dependabot[bot]'
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Hello @${{ github.actor }}! Thanks for contributing to the plugin!
                        
            Your PR basically need 3 things to be merged:
              - Your PR title need to follow the [conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/)
              - It must transpile without error and be tested
              - An approbation

  check_title:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
